<?php
$_productCollection = $this->getLoadedProductCollection();
$columnCount = themeOptions('column_count');
$hoverSwap = themeOptions('hover_swap');
$enableAjax = themeOptions('enable_ajax');
$this->setColumnCount($columnCount);
$_helper = $this->helper('catalog/output');
$model = Mage::getModel('catalog/product'); //getting product model

$_products = $this->getCustomProductList(array(1, 2));
?>


<?php if ($_products): ?>
	<?php foreach ($_products AS $prod): ?>
		<?php $_product = $model->load($prod['entity_id']); ?>

		<?php $extra = $_product->getExtraInfo(); ?>
		<div>
			<?php if ($extra): ?>
				<div style="visibility:hidden;">
					<span id="video-link-<?= $prod['entity_id']; ?>" class="video-link" data-video-id="<?= $extra[0]['video_id']; ?>">
						Play Video
					</span>	
				</div>
			<?php endif; ?>
		</div>
	<?php endforeach; ?>
<?php endif; ?>

<div id="ioSliderDiv" style="position:relative;">
	<div class="iosSlider">  
		<div class="slider">  
			<div class="slide"><img class="royalImage" src="/skin/frontend/default/blanco/images/catalog/product/slider/kids-on-grass-2.jpg" alt="" /></div>
			<div class="slide"><img class="royalImage" src="/skin/frontend/default/blanco/images/catalog/product/slider/kids children toys 4916x3206 wallpaper_www.wallpaperfo.com_63.jpg" alt="" /></div>
			<?php if ($_products): ?>
				<?php foreach ($_products AS $prod): ?>

					<?php
					$_product = $model->load($prod['entity_id']);

					echo "<div class='slide'><img class='royalImage' src='" . stripslashes($prod['image_slider']) . "' /></div>";
					?>
				<?php endforeach; ?>
			<?php endif; ?>
		</div>
		<div class="sliderNavi"><span class="naviItem selected">1</span> <span class="naviItem">2</span> <span class="naviItem">3</span> <span class="naviItem">4</span><span class="naviItem">5</span></div>
		<div class="prev">&nbsp;</div>
		<div class="next">&nbsp;</div>
	</div>
</div>



<script type="text/javascript">
	jQuery(document).ready(function(){
		jQuery(document).on('click', '.play-vid', function(){
			var videoId = parseInt(jQuery(this).data('vidid'));
			console.log(videoId)
			jQuery('#video-link-' + videoId).trigger('click');
		});
	});
</script>


<div class="clear">
	<h5 style="float: left; border: 1px solid #EFEFEF; padding: 4px 15px; margin: 13px 0 0 20px; border-bottom: 0;">NEW PRODUCTS</h5>
	<div class="clear" style="border-top: 1px solid #EFEFEF; height: 13px;">&nbsp;</div>
	<!--{{block type="catalog/product_new" name="blanco.catalog.product.new" alias="product_homepage" template="catalog/product/new.phtml"}}-->
	<div class="newproducts">
        <div class="carousel" style="position: relative; top: 0px; left: 0px; overflow: hidden; z-index: 1; width: 714px; height: 318px;">
            <div class="slider" style="-webkit-perspective: 1000px; -webkit-backface-visibility: hidden; position: relative; cursor: -webkit-grab; width: 5213px; overflow: hidden; -webkit-transform: translateX(0px);">



<!--					<a href="http://8theme.com/demo/blanco/fashion-demo-shoes-619.html" title="Fashion Demo Shoes" class="product-image"><img src="http://8theme.com/demo/blanco/media/catalog/product/cache/1/small_image/210x/9df78eab33525d08d6e5fb8d27136e95/1/_/1.1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_2_1.jpg" width="210" height="210" alt="Fashion Demo Shoes"></a>
					<div class="new-description">
						<h3><a href="http://8theme.com/demo/blanco/fashion-demo-shoes-619.html" title="Fashion Demo Shoes">Fashion Demo Shoes</a></h3>



						<div class="price-box">

							<p class="old-price">
								<span class="price-label">Regular Price:</span>
								<span class="price" id="old-price-311">
									$1,190.00                </span>
							</p>

							<p class="special-price">
								<span class="price-label">Special Price:</span>
								<span class="price" id="product-price-311">
									$999.00                </span>
							</p>


						</div>



						<button type="button" title="Add to Cart" class="button btn-cart" onclick="setLocation('http://8theme.com/demo/blanco/fashion-demo-shoes-619.html?options=cart')"><span><span>Add to Cart</span></span></button>
						<div style="clear: both;"></div>
					</div>                    
				</div>-->

				
				<?php if ($_products): ?>
					<?php foreach ($_products AS $prod): ?>
						<?php $_product = $model->load($prod['entity_id']); ?>
						<div class="item slide " style="width: 233px; float: left;"> 
							<a href="<?= $_product->getProductUrl(); ?>" title="<?= $_product->getName(); ?>" class="product-image"><img src="<?= $_product['image_slider']; ?>" width="210" height="210" alt="<?= $_product->getName(); ?>"></a>
							<div class="new-description">
								<h3><a href="<?= $_product->getProductUrl(); ?>" title="<?= $_product->getName(); ?>"><?= $_product->getName(); ?></a></h3>

								<p class="special-price">
									<span class="price-label">Price:</span>
									<span class="price" id="product-price-311">
										<?= number_format($_product->getPrice(), 2); ?>           
									</span>
								</p>

								<!--<?php $extra = $_product->getExtraInfo(); ?>

								<?php if ($extra): ?>
									<div>
										<span class="play-vid" data-vidid="<?= $prod['entity_id']; ?>" style='display:block;width:70px;margin:0 auto; width:100%;text-align:center;background-color:rgb(230, 230, 230);clear:both;cursor:pointer;'>
											Play Video
										</span>	
									</div>
								<?php endif; ?>-->

							</div>

						</div>
					<?php endforeach; ?>
				<?php endif; ?>
				
				
				
				
				
				
				
				
				
				
				
				
<!--				<div class="item slide " style="width: 233px; float: left;"> 
					<div class="newproduct_grid">New</div>
                    <div class="saleproduct ">Sale</div>

					<div class="ratings">
						<div class="rating-box">
							<div class="rating" style="width:100%"></div>
						</div>
						<span class="amount"><a href="#" onclick="var t = opener ? opener.window : window;
								t.location.href = 'http://8theme.com/demo/blanco/review/product/list/id/301/';
								return false;">1 Review(s)</a></span>
					</div>

					<a href="http://8theme.com/demo/blanco/simple-fashion-shoes.html" title="Simple Fashion Shoes" class="product-image"><img src="http://8theme.com/demo/blanco/media/catalog/product/cache/1/small_image/210x/9df78eab33525d08d6e5fb8d27136e95/4/_/4.1_1_1_1_1_1_1_1_1_1_1_1.jpg" width="210" height="210" alt="Simple Fashion Shoes"></a>
					<div class="new-description">
						<h3><a href="http://8theme.com/demo/blanco/simple-fashion-shoes.html" title="Simple Fashion Shoes">Simple Fashion Shoes</a></h3>



						<div class="price-box">

							<p class="old-price">
								<span class="price-label">Regular Price:</span>
								<span class="price" id="old-price-301">
									$915.00                </span>
							</p>

							<p class="special-price">
								<span class="price-label">Special Price:</span>
								<span class="price" id="product-price-301">
									$790.00                </span>
							</p>


						</div>



						<button type="button" title="Add to Cart" class="button btn-cart" onclick="setLocation('http://8theme.com/demo/blanco/simple-fashion-shoes.html?options=cart')"><span><span>Add to Cart</span></span></button>
						<div style="clear: both;"></div>
					</div>                    
				</div>
				<div class="item slide " style="width: 233px; float: left;"> 
					<div class="newproduct_grid">New</div>
                    <div class="saleproduct ">Sale</div>

					<div class="ratings">
						<div class="rating-box">
							<div class="rating" style="width:47%"></div>
						</div>
						<span class="amount"><a href="#" onclick="var t = opener ? opener.window : window;
								t.location.href = 'http://8theme.com/demo/blanco/review/product/list/id/328/';
								return false;">1 Review(s)</a></span>
					</div>

					<a href="http://8theme.com/demo/blanco/nice-t-shirts.html" title="Nice T-shirts" class="product-image"><img src="http://8theme.com/demo/blanco/media/catalog/product/cache/1/small_image/210x/9df78eab33525d08d6e5fb8d27136e95/1/3/13.1_3.jpg" width="210" height="210" alt="Nice T-shirts"></a>
					<div class="new-description">
						<h3><a href="http://8theme.com/demo/blanco/nice-t-shirts.html" title="Nice T-shirts">Nice T-shirts</a></h3>



						<div class="price-box">

							<p class="old-price">
								<span class="price-label">Regular Price:</span>
								<span class="price" id="old-price-328">
									$1,800.00                </span>
							</p>

							<p class="special-price">
								<span class="price-label">Special Price:</span>
								<span class="price" id="product-price-328">
									$1,499.00                </span>
							</p>


						</div>



						<button type="button" title="Add to Cart" class="button btn-cart" onclick="setLocation('http://8theme.com/demo/blanco/nice-t-shirts.html?options=cart')"><span><span>Add to Cart</span></span></button>
						<div style="clear: both;"></div>
					</div>                    
				</div>
				<div class="item slide " style="width: 233px; float: left;"> 
					<div class="newproduct_grid">New</div>

					<div class="ratings">
						<div class="rating-box">
							<div class="rating" style="width:40%"></div>
						</div>
						<span class="amount"><a href="#" onclick="var t = opener ? opener.window : window;
								t.location.href = 'http://8theme.com/demo/blanco/review/product/list/id/296/';
								return false;">1 Review(s)</a></span>
					</div>

					<a href="http://8theme.com/demo/blanco/demo-fashion-shoes.html" title="Demo Fashion Shoes" class="product-image"><img src="http://8theme.com/demo/blanco/media/catalog/product/cache/1/small_image/210x/9df78eab33525d08d6e5fb8d27136e95/9/_/9.1_2_1_1_1_1_1_1.jpg" width="210" height="210" alt="Demo Fashion Shoes"></a>
					<div class="new-description">
						<h3><a href="http://8theme.com/demo/blanco/demo-fashion-shoes.html" title="Demo Fashion Shoes">Demo Fashion Shoes</a></h3>



						<div class="price-box">
							<span class="regular-price" id="product-price-296">
								<span class="price">$1,019.90</span>                                    </span>

						</div>




						<button type="button" title="Add to Cart" class="button btn-cart" onclick="setLocation('http://8theme.com/demo/blanco/nice-fashion-jacket.html?options=cart')"><span><span>Add to Cart</span></span></button>
						<div style="clear: both;"></div>
					</div>                    
				</div>-->
			</div>             
        </div>
		<div class="prev new-arrow disabled" style="cursor: pointer;">&nbsp;</div>
		<div class="next new-arrow" style="cursor: pointer;">&nbsp;</div>  
	</div>
</div>

<script type="text/javascript">
		jQuery(document).ready(function(){
			 jQuery(".video-link").jqueryVideoLightning({
				autoplay: 1,
				backdrop_color: "#ddd",
				backdrop_opacity: 0.6,
				glow: 20,
				glow_color: "#000"
			});
		});
</script>